# Generated by Django 3.0.3 on 2020-03-08 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='polarity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
