# Generated by Django 3.0.3 on 2020-03-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0002_post_polarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='polarity',
            field=models.BinaryField(),
        ),
    ]
