# Generated by Django 3.0.3 on 2020-03-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0003_auto_20200308_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='polarity',
            field=models.IntegerField(),
        ),
    ]
