# Generated by Django 3.0.3 on 2020-03-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0004_auto_20200308_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='polarity',
            field=models.IntegerField(null=True),
        ),
    ]
