# Generated by Django 3.0.4 on 2020-03-14 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0005_auto_20200308_0703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='polarity',
        ),
    ]
